// Tactical Roles with emblems, colors, and skill multipliers
export const ROLES = {
  captain: {
    id: 'captain',
    nameEn: 'Captain',
    nameAr: 'قائد الفريق',
    icon: 'Crown',
    color: '#fbbf24',
    bg: 'rgba(251, 191, 36, 0.18)',
    border: 'rgba(251, 191, 36, 0.4)',
  },
  striker: {
    id: 'striker',
    nameEn: 'Striker / Carry',
    nameAr: 'مهاجم / حاسم',
    icon: 'Zap',
    color: '#f43f5e',
    bg: 'rgba(244, 63, 94, 0.18)',
    border: 'rgba(244, 63, 94, 0.4)',
  },
  tank: {
    id: 'tank',
    nameEn: 'Defender / Tank',
    nameAr: 'مدافع / مدرع',
    icon: 'Shield',
    color: '#3b82f6',
    bg: 'rgba(59, 130, 246, 0.18)',
    border: 'rgba(59, 130, 246, 0.4)',
  },
  support: {
    id: 'support',
    nameEn: 'Support / Healer',
    nameAr: 'دعم / مساند',
    icon: 'HeartHandshake',
    color: '#10b981',
    bg: 'rgba(16, 185, 129, 0.18)',
    border: 'rgba(16, 185, 129, 0.4)',
  },
  playmaker: {
    id: 'playmaker',
    nameEn: 'Playmaker / Mid',
    nameAr: 'صانع ألعاب / وسط',
    icon: 'Sparkles',
    color: '#8b5cf6',
    bg: 'rgba(139, 92, 246, 0.18)',
    border: 'rgba(139, 92, 246, 0.4)',
  },
  rookie: {
    id: 'rookie',
    nameEn: 'Rookie / Sub',
    nameAr: 'مستجد / بديل',
    icon: 'Target',
    color: '#06b6d4',
    bg: 'rgba(6, 182, 212, 0.18)',
    border: 'rgba(6, 182, 212, 0.4)',
  },
};

// Preset Rosters for Quick Play
export const PRESETS = [
  {
    id: 'football-5v5',
    titleAr: 'كرة قدم 5 ضد 5 (10 لاعبين)',
    titleEn: 'Football 5v5 (10 Players)',
    icon: 'Trophy',
    category: 'sports',
    members: [
      { id: 'f1', name: 'طارق الأسطورة', role: 'captain', level: 9, notes: 'تسديدات صاروخية' },
      { id: 'f2', name: 'كريم الصخرة', role: 'tank', level: 8, notes: 'قلب دفاع صلب' },
      { id: 'f3', name: 'ياسين الساحر', role: 'playmaker', level: 9, notes: 'تمريرات حاسمة' },
      { id: 'f4', name: 'سامي الهداف', role: 'striker', level: 8, notes: 'إنهاء هجمات ممتاز' },
      { id: 'f5', name: 'أحمد الجدار', role: 'support', level: 7, notes: 'حارس يقظ' },
      { id: 'f6', name: 'فيصل الكابيتانو', role: 'captain', level: 9, notes: 'تنظيم تكتيكي عالي' },
      { id: 'f7', name: 'وليد المتراس', role: 'tank', level: 8, notes: 'تغطية دفاعية ذكية' },
      { id: 'f8', name: 'عمر المايسترو', role: 'playmaker', level: 8, notes: 'رؤية للملعب' },
      { id: 'f9', name: 'ماجد القناص', role: 'striker', level: 9, notes: 'سرعة ودقة' },
      { id: 'f10', name: 'سعود الطائر', role: 'support', level: 7, notes: 'ركض وتغطية' },
    ],
  },
  {
    id: 'esports-squad',
    titleAr: 'بطولة eSports (8 لاعبين)',
    titleEn: 'eSports Valorant / CS (8 Players)',
    icon: 'Gamepad2',
    category: 'gaming',
    members: [
      { id: 'e1', name: 'ShadowIGL', role: 'captain', level: 10, notes: 'Shot caller & clutches' },
      { id: 'e2', name: 'CyberAim', role: 'striker', level: 9, notes: 'First entry fragger' },
      { id: 'e3', name: 'ViperSmoke', role: 'support', level: 8, notes: 'Controller smokes' },
      { id: 'e4', name: 'IronShield', role: 'tank', level: 7, notes: 'Anchor site B' },
      { id: 'e5', name: 'NeonPhantom', role: 'captain', level: 9, notes: 'Dualist specialist' },
      { id: 'e6', name: 'PixelSniper', role: 'striker', level: 9, notes: 'AWP master' },
      { id: 'e7', name: 'AegisWall', role: 'tank', level: 8, notes: 'Flash and recon' },
      { id: 'e8', name: 'NovaFlash', role: 'playmaker', level: 8, notes: 'Lurker & flanker' },
    ],
  },
  {
    id: 'padel-2v2',
    titleAr: 'بطولة بادل 2 ضد 2 (8 لاعبين)',
    titleEn: 'Padel 2v2 (8 Players)',
    icon: 'Activity',
    category: 'sports',
    members: [
      { id: 'p1', name: 'خالد ريفليكس', role: 'striker', level: 9, notes: 'سماش هوائي قوي' },
      { id: 'p2', name: 'بدر الزجاجي', role: 'tank', level: 8, notes: 'لعب زوايا وجدران' },
      { id: 'p3', name: 'زياد اللوب', role: 'playmaker', level: 9, notes: 'ضربات ساقطة دقيقة' },
      { id: 'p4', name: 'معاذ الفولي', role: 'support', level: 7, notes: 'رد فعل شبكي' },
      { id: 'p5', name: 'فهد البانديخا', role: 'striker', level: 9, notes: 'دقة عالية' },
      { id: 'p6', name: 'سلطان الدفاع', role: 'tank', level: 8, notes: 'تغطية خلفية' },
      { id: 'p7', name: 'نايف السيرف', role: 'playmaker', level: 8, notes: 'إرسال مباغت' },
      { id: 'p8', name: 'حمد السريع', role: 'rookie', level: 7, notes: 'لياقة عالية' },
    ],
  },
  {
    id: 'work-squad',
    titleAr: 'فريق العمل والهاكاثون (6 أعضاء)',
    titleEn: 'Innovation Hackathon (6 Members)',
    icon: 'Users',
    category: 'work',
    members: [
      { id: 'w1', name: 'سارة القيادية', role: 'captain', level: 10, notes: 'Product Strategy' },
      { id: 'w2', name: 'أمين المطور', role: 'striker', level: 9, notes: 'Full-stack Architect' },
      { id: 'w3', name: 'منى المصممة', role: 'playmaker', level: 9, notes: 'UI/UX & Motion' },
      { id: 'w4', name: 'حسام المحلل', role: 'support', level: 8, notes: 'Data & Growth' },
      { id: 'w5', name: 'ليلى الباحثة', role: 'tank', level: 8, notes: 'User Testing' },
      { id: 'w6', name: 'ريان المبتكر', role: 'rookie', level: 8, notes: 'Pitch & Deck' },
    ],
  },
];

// Oracle Preset Question Cards
export const ORACLE_PRESETS = [
  {
    id: 'who-starts',
    questionAr: 'مين يبدأ أولاً في الجيم؟',
    questionEn: 'Who starts the game first?',
    icon: 'PlayCircle',
    optionsAr: ['الفريق الأزرق', 'الفريق البنفسجي', 'صاحب أعلى مهارة', 'أصغر لاعب عمراً'],
    optionsEn: ['Blue Team', 'Purple Team', 'Highest Skill Player', 'Youngest Player'],
  },
  {
    id: 'what-food',
    questionAr: 'إيش ناكل بعد المباراة؟',
    questionEn: 'What food after match?',
    icon: 'UtensilsCrossed',
    optionsAr: ['شاورما ومشاوي 🌯', 'برجر وعصيرات 🍔', 'بيتزا إيطالية 🍕', 'أكل صحي وسلطات 🥗'],
    optionsEn: ['Shawarma & Grills 🌯', 'Burgers & Shakes 🍔', 'Artisan Pizza 🍕', 'Healthy & Bowls 🥗'],
  },
  {
    id: 'which-game',
    questionAr: 'أي لعبة نلعب الليلة؟',
    questionEn: 'Which game to play tonight?',
    icon: 'Gamepad',
    optionsAr: ['فيفا / EA FC ⚽', 'فالورانت / Valorant 🎯', 'بادل لايف 🎾', 'بورد جيمز / كود نيمز 🎲'],
    optionsEn: ['EA Sports FC ⚽', 'Valorant / CS 🎯', 'Live Padel 🎾', 'Board Games / Codenames 🎲'],
  },
  {
    id: 'match-field',
    questionAr: 'في أي ملعب نلعب؟',
    questionEn: 'Which arena to book?',
    icon: 'MapPin',
    optionsAr: ['ملعب الأساطير المغلق', 'ساحة النجوم العشبية', 'أكاديمية البادل الدولية', 'ملعب السيتي المفتوح'],
    optionsEn: ['Legends Indoor Arena', 'Stars Turf Stadium', 'Padel Pro Academy', 'City Open Field'],
  },
];
