import React, { createContext, useContext, useState, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const TRANSLATIONS = {
  ar: {
    nav: {
      home: 'الرئيسية',
      members: 'اللعيبة',
      generate: 'توزيع الفرق',
      tournament: 'البطولة',
      finger: 'القرعة',
      oracle: 'عجلة الحظ',
      history: 'السجل',
      settings: 'الإعدادات',
    },
    header: {
      appName: 'TEAM ME PRO',
      tagline: 'محرك الفرق الذكي',
    },
    home: {
      heroBadge: 'توزيع الفرق والبطولات بذكاء',
      heroTitle1: 'شَكِّلْ فَرِيقَكْ',
      heroTitle2: 'بِأَعْلَى تَوَازُنْ',
      heroSubtitle: 'أسهل وأسرع تطبيق لتنظيم فرق الماتشات، البادل، والألعاب بأعلى توازن في ثواني.',
      ctaGenerate: 'وزّع الفرق دلوقتي',
      ctaMembers: 'قائمة اللعيبة',
      ctaTournament: 'شجرة البطولة',
      ctaFinger: 'قرعة الصوابع',
      liveDemoTitle: 'معاينة سريعة',
      liveDemoSubtitle: 'توزيع فوري متوازن مع مؤشرات القوة',
      shuffleBtn: 'خلط الفرق',
      teamA: 'فريق الصقور (أزرق)',
      teamB: 'فريق الفرسان (بنفسجي)',
      avgPower: 'متوسط القوة',
      totalSkill: 'مجموع المهارة',
      quickStats: 'إحصائيات',
      statMembers: 'اللعيبة المسجلة',
      statBalanced: 'تشكيلات متوازنة',
      statSpeed: 'سرعة التوزيع',
      featuresTitle: 'مميزات التطبيق',
      feat1Title: '4 طرق توزيع ذكية',
      feat1Desc: 'عشوائي، متوازن بالمهارة، الكباتن أولاً، وحسب المراكز.',
      feat2Title: 'مظاهر وثيمات متميزة',
      feat2Desc: 'أوبسيديان داكن، مانجا بيبر، نيبولا، سايبر، ورويال.',
      feat3Title: 'بطولات وقرعة صوابع',
      feat3Desc: 'شجرة مواجهات مع تتويج الفائز، وقرعة لمس الصوابع.',
      quickStartTitle: 'بداية سريعة',
      quickStartDesc: 'حمل تشكيلة جاهزة وابدأ الماتش فوراً.',
      loadFootball: 'ماتش خماسي 5 ضد 5',
      loadEsports: 'فريق ألعاب eSports',
      loadPadel: 'ماتش بادل 2 ضد 2',
    },
    members: {
      title: 'قائمة اللعيبة',
      subtitle: 'سجل اللعيبة وحدد مراكزهم ومستوى لعبهم عشان الماتشات تطلع متوازنة',
      searchPlaceholder: 'ابحث عن لاعب بالاسم...',
      allRoles: 'كل المراكز',
      addMemberBtn: 'إضافة لاعب جديد +',
      bulkImportBtn: 'استيراد أسماء',
      presetsBtn: 'نماذج جاهزة',
      emptyTitle: 'مفيش لعيبة متسجلة لسه',
      emptySubtitle: 'أضف أول لاعب في قائمتك عشان تبدأ توزع الفرق وتعمل بطولات.',
      level: 'المستوى',
      stars: 'النجوم',
      edit: 'تعديل',
      delete: 'مسح',
      notes: 'ملاحظات',
      addModalTitle: 'إضافة لاعب جديد',
      editModalTitle: 'تعديل بيانات اللاعب',
      nameLabel: 'اسم اللاعب *',
      namePlaceholder: 'مثال: كريم الصخرة، سارة الهداف...',
      roleLabel: 'المركز التكتيكي',
      levelLabel: 'مستوى اللعب (1 - 10)',
      notesLabel: 'ملاحظات إضافية',
      notesPlaceholder: 'مثال: سريع، دفاع قوي، صانع لعب...',
      saveBtn: 'حفظ وتأكيد',
      cancelBtn: 'إلغاء',
      bulkModalTitle: 'استيراد مجموعة لعيبة مع بعض',
      bulkModalSubtitle: 'الصق أسماء اللعيبة (كل اسم في سطر مستقل):',
      bulkPlaceholder: 'طارق الأسطورة\nكريم الصخرة\nياسين الساحر\nسامي الهداف...',
      bulkImportSubmit: 'استيراد الأسماء',
      presetLoadedSuccess: 'تم تحميل اللعيبة بنجاح!',
    },
    generate: {
      title: 'توزيع وتشكيل الفرق',
      subtitle: 'اختر عدد الفرق وطريقة التوزيع المناسبة لماتشكم',
      teamCountLabel: 'عايز كام فريق؟',
      algoLabel: 'طريقة التوزيع والتوازن',
      algoRandom: 'عشوائي تماماً',
      algoRandomDesc: 'خلط عشوائي وسريع',
      algoBalanced: 'متوازن بالمهارة (Snake Draft)',
      algoBalancedDesc: 'توازن دقيق لقوة اللعيبة بين الفرق',
      algoCaptains: 'الكباتن أولاً',
      algoCaptainsDesc: 'فصل الكباتن ثم توزيع باقي اللعيبة',
      algoRoles: 'حسب المراكز',
      algoRolesDesc: 'توزيع المهاجمين والمدافعين بالتساوي',
      togglesTitle: 'إضافات الجلسة',
      toggleTimer: 'ساعة الماتش',
      toggleSound: 'الأصوات',
      toggleScore: 'لوحة الأهداف',
      toggleStats: 'مؤشرات القوة',
      toggleConfetti: 'احتفال عند التوزيع',
      ctaGenerate: 'وزّع الفرق دلوقتي  ',
      ctaCharging: 'جاري توزيع الفرق...',
      teamsGeneratedTitle: 'التشكيلات المولّدة',
      swapHint: '💡 ميزة التبديل: اضغط على أي لاعب ثم لاعب تاني لتبديل مركزيهما فوراً.',
      selectedForSwap: 'تم تحديد اللاعب. اضغط على لاعب تاني لإتمام التبديل.',
      shareWhatsapp: 'مشاركة على واتساب 📱',
      exportJson: 'تصدير JSON',
      saveHistory: 'حفظ في السجل',
      launchTournament: 'بدء بطولة بالفرق دي',
      matchTimerTitle: 'ساعة الماتش',
      min5: '5 دقايق',
      min10: '10 دقايق',
      min15: '15 دقيقة',
      timerStart: 'ابدأ الماتش',
      timerPause: 'إيقاف مؤقت',
      timerReset: 'إعادة ضبط',
      copiedSuccess: 'تم نسخ التشكيلة لمشاركتها على واتساب!',
      savedHistorySuccess: 'تم حفظ التشكيلة في السجل بنجاح!',
      notEnoughMembers: 'محتاج تضيف لاعبين اتنين على الأقل لتوليد الفرق.',
    },
    tournament: {
      title: 'شجرة البطولة والماتشات',
      subtitle: 'مواجهات إقصائية خروج مغلوب ومتابعة النتيجة لحد التتويج',
      createBtn: 'بدء بطولة بالفرق الحالية 🏆',
      resetBtn: 'إعادة ضبط البطولة',
      quarterFinals: 'دور الـ 8',
      semiFinals: 'نصف النهائي',
      grandFinal: 'النهائي الكبير',
      advanceWinner: 'تأهيل الفائز ➜',
      matchScore: 'النتيجة',
      vs: 'ضد',
      winner: 'فائز',
      tbd: 'في انتظار المتأهل...',
      championTitle: '🏆 بطل البطولة! 👑',
      championSubtitle: 'ألف مبروك للفريق الفائز باللقب بعد ماتشات أسطورية!',
      closeChampion: 'إغلاق ومتابعة',
      noTournamentTitle: 'مفيش بطولة نشطة حالياً',
      noTournamentSubtitle: 'وزّع الفرق الأول وبعدين اضغط "بدء بطولة" لعمل شجرة المواجهات أوتوماتيكياً.',
    },
    finger: {
      title: 'قرعة لمس الصوابع',
      subtitle: 'حطوا صوابعكم على الشاشة مع بعض والقرعة هتختار الفائز في ثواني',
      modeLabel: 'نوع القرعة',
      modeWinners: 'اختيار فائزين',
      modePairs: 'مين مع مين (ثنائيات)',
      modeTeams: 'تقسيم لفرق',
      winnersCount: 'عايز كام فائز؟',
      teamsCount: 'عايز كام فريق؟',
      waitingMessage: 'حطوا صوابعكم على الشاشة مع بعض',
      waitingHint: 'لازم صباعين على الأقل عشان يبدأ العد التنازلي',
      activeTouches: 'الصوابع الموجودة على الشاشة',
      countdown: 'استعدوا...',
      simulateBtn: 'تجربة القرعة',
      clearTouches: 'مسح الصوابع ✕',
      resultTitle: 'نتيجة القرعة المحسومة!',
      winnerBadge: 'فائز بالقرعة 👑',
      pairBadge: 'ثنائي مع بعض 🤝',
      teamBadge: 'فريق',
      againBtn: 'سحب جديد 🔄',
    },
    oracle: {
      title: 'عجلة الحظ والقرعة',
      subtitle: 'لف العجلة لحسم مين يبدأ الماتش، مين يشتري، أو أي اختيار محتارين فيه',
      inputPlaceholder: 'اكتب اختيار جديد هنا...',
      addOptionBtn: 'إضافة +',
      quickQuestions: 'أفكار سريعة:',
      currentOptions: 'الخيارات الحالية:',
      minOptionsHint: 'أضف اختيارين على الأقل عشان تلف العجلة',
      ctaDecide: 'لف العجلة دلوقتي',
      step1: 'جاري تحليل الاختيارات...',
      step2: 'جاري تشغيل محرك الاحتمالات...',
      step3: 'تم حسم الاختيار!',
      decisionTitle: 'الاختيار وقع على:',
      decideAgain: 'سحب جديد 🎲',
    },
    history: {
      title: 'سجل التشكيلات المحفوظة',
      subtitle: 'أرشيف بكل التشكيلات والماتشات اللي وزعتها قبل كده',
      emptyTitle: 'السجل فاضي لسه',
      emptySubtitle: 'لما توزع أي فرق وتدوس "حفظ في السجل"، هتظهر هنا عشان ترجعلها في أي وقت.',
      clearAllBtn: 'مسح كل السجل 🗑️',
      restoreBtn: 'استرجاع التشكيلة 🔄',
      deleteBtn: 'مسح',
      savedOn: 'تم الحفظ في',
      membersCount: 'لعيبة',
      teamsCount: 'فرق',
      confirmClearTitle: 'هل أنت متأكد من مسح كل السجل؟',
      confirmClearDesc: 'الإجراء ده هيمسح كل التشكيلات المؤرشفة نهائياً.',
      confirmYes: 'أيوة، امسح الكل',
      confirmCancel: 'إلغاء',
    },
    settings: {
      title: 'الإعدادات والمظهر',
      subtitle: 'تخصيص المظهر، الأصوات، اللغة، وإدارة البيانات',
      themeSection: 'المظهر والثيم',
      themeApplied: 'المظهر النشط',
      applyThemeBtn: 'تطبيق المظهر',
      soundSection: 'المؤثرات الصوتية والاهتزاز',
      soundTitle: 'الصوت والاهتزاز اللمسي',
      soundDesc: 'أصوات النقر والنتائج وتدوير العجلة والتتويج',
      soundOn: 'مفعّل',
      soundOff: 'مكتوم',
      langSection: 'لغة التطبيق',
      langArabic: 'العربية',
      langEnglish: 'English',
      backupSection: 'النسخ الاحتياطي وإدارة البيانات',
      backupDesc: 'احفظ بيانات اللعيبة والتشكيلات في ملف خارجي أو استرجعه',
      exportJsonBtn: 'تصدير نسخة احتياطية (JSON)',
      importJsonBtn: 'استيراد بيانات سابقة',
      dangerSection: 'منطقة الخطر',
      factoryResetBtn: 'مسح كل البيانات والبدء من الصفر ⚠️',
      aboutSection: 'عن التطبيق',
      aboutText: 'TEAM ME PRO هو تطبيق رياضي وترفيهي متقدم مصمم لتنظيم الماتشات والفرق الرياضية بأعلى توازن.',
      version: 'الإصدار 2.5.0 — النسخة الاحترافية',
      resetModalTitle: 'تحذير مسح البيانات',
      resetModalDesc: 'سيتم مسح كل اللعيبة والفرق والسجل والبدء من الصفر. هل تريد المتابعة؟',
      resetModalConfirm: 'أيوة، امسح كل البيانات',
    },
  },
  en: {
    nav: {
      home: 'Home',
      members: 'Members',
      generate: 'Generate',
      tournament: 'Tournament',
      finger: 'Finger',
      oracle: 'Oracle',
      history: 'History',
      settings: 'Settings',
    },
    header: {
      appName: 'TEAM ME PRO',
      tagline: 'Smart Sports-Tech Engine 2026',
    },
    home: {
      heroBadge: '  Smart Sports-Tech & Esports Roster Generator',
      heroTitle1: 'BUILD YOUR TEAM',
      heroTitle2: 'WITH PURE INTELLIGENCE',
      heroSubtitle: 'The ultimate 2026 platform for organizing football, padel, basketball, eSports, and competitive group rosters with balanced algorithms and futuristic glassmorphic UI.',
      ctaGenerate: 'Generate Teams Now',
      ctaMembers: 'Manage Elite Roster',
      ctaTournament: 'Tournament System 🏆',
      ctaFinger: 'Finger Chooser 👆',
      liveDemoTitle: 'Interactive Live Demo',
      liveDemoSubtitle: 'Instant balanced distribution with tactical power meters',
      shuffleBtn: 'Shuffle Teams Now 🎲',
      teamA: 'Team Falcons (Blue)',
      teamB: 'Team Knights (Purple)',
      avgPower: 'Avg Power',
      totalSkill: 'Total Skill',
      quickStats: 'System Metrics',
      statMembers: 'Total Members',
      statBalanced: 'Balanced Rosters',
      statSpeed: 'Engine Speed',
      featuresTitle: 'Next-Gen 2026 Features',
      feat1Title: '4 Smart Algorithms',
      feat1Desc: 'Pure random, Snake-Draft skill balanced, Captains first, and tactical Role balance.',
      feat2Title: '7 Epic Glass Themes',
      feat2Desc: 'Nebula, Pure Frost, Obsidian Dark, Royal Gold, Emerald Aurora, Cyber HUD, and Crimson.',
      feat3Title: 'Tournament & Hologram Draw',
      feat3Desc: 'Esports elimination bracket with coronation modal, and laser multi-touch finger chooser.',
      quickStartTitle: 'One-Tap Quick Start',
      quickStartDesc: 'Load a curated roster preset and generate balanced teams in under 3 seconds.',
      loadFootball: 'Football 5v5 Roster',
      loadEsports: 'eSports Valorant Roster',
      loadPadel: 'Padel 2v2 Roster',
    },
    members: {
      title: 'Elite Members Management',
      subtitle: 'Register players, assign tactical roles, and calibrate skill levels to guarantee balanced matches',
      searchPlaceholder: 'Search players by name or notes...',
      allRoles: 'All Roles',
      addMemberBtn: 'Add New Member +',
      bulkImportBtn: 'Bulk Import 📋',
      presetsBtn: 'Roster Presets  ',
      emptyTitle: 'No Members Registered',
      emptySubtitle: 'Add your first player or load a curated preset pack to populate instantly.',
      level: 'Skill Level',
      stars: 'Stars',
      edit: 'Edit',
      delete: 'Delete',
      notes: 'Notes',
      addModalTitle: 'Add New Member',
      editModalTitle: 'Edit Member Details',
      nameLabel: 'Player / Member Name *',
      namePlaceholder: 'e.g., Alex Striker, Leo Playmaker...',
      roleLabel: 'Tactical Role',
      levelLabel: 'Skill Level (1 - 10)',
      notesLabel: 'Tactical Notes (Position / Traits)',
      notesPlaceholder: 'e.g., Power shot, Rock defense, Playmaker...',
      saveBtn: 'Save & Confirm',
      cancelBtn: 'Cancel',
      bulkModalTitle: 'Bulk Import Members',
      bulkModalSubtitle: 'Paste player names (one per line or comma-separated):',
      bulkPlaceholder: 'Tariq Legend\nKarim Rock\nYassine Magician\nSami Striker...',
      bulkImportSubmit: 'Import & Parse Names',
      presetLoadedSuccess: 'Preset roster successfully loaded!',
    },
    generate: {
      title: 'Smart Team Generator Engine',
      subtitle: 'Select team count and the optimal balancing algorithm for your sport or gaming activity',
      teamCountLabel: 'Desired Number of Teams',
      algoLabel: 'Balancing Algorithm',
      algoRandom: 'Pure Random (Fisher-Yates)',
      algoRandomDesc: 'Pure uniform shuffle for casual play',
      algoBalanced: 'Skill Balanced (Snake Draft)',
      algoBalancedDesc: 'Rigorous skill sum equalization',
      algoCaptains: 'Captains First (Captains)',
      algoCaptainsDesc: 'Isolate captains then balance remaining',
      algoRoles: 'Role Balanced (Roles)',
      algoRolesDesc: 'Equally distribute Strikers, Tanks & Supports',
      togglesTitle: 'Session Features & Effects',
      toggleTimer: 'Match Timer',
      toggleSound: 'Sound FX',
      toggleScore: 'Scoreboard',
      toggleStats: 'Power Gauges',
      toggleConfetti: 'Auto Confetti',
      ctaGenerate: 'Generate Teams Now  ',
      ctaCharging: 'Computing Optimal Rosters...',
      teamsGeneratedTitle: 'Generated Teams',
      swapHint: '💡 Swap Feature: Tap any player card, then tap another player on a different team to swap them instantly.',
      selectedForSwap: 'Player selected for swap. Tap another player to complete the transfer.',
      shareWhatsapp: 'Share to WhatsApp 📱',
      exportJson: 'Export JSON 📄',
      saveHistory: 'Save to History 💾',
      launchTournament: 'Create Tournament 🏆',
      matchTimerTitle: 'Tactical Match Countdown',
      min5: '5 Mins',
      min10: '10 Mins',
      min15: '15 Mins',
      timerStart: 'Start Match',
      timerPause: 'Pause',
      timerReset: 'Reset',
      copiedSuccess: 'Roster text copied to clipboard for WhatsApp!',
      savedHistorySuccess: 'Current roster saved to History archive!',
      notEnoughMembers: 'You need at least 2 members to generate teams.',
    },
    tournament: {
      title: 'Esports Elimination Tournament',
      subtitle: 'Interactive bracket visualization to track scores, advance winners, and crown champions',
      createBtn: 'Build Bracket from Current Teams 🏆',
      resetBtn: 'Reset Tournament 🔄',
      quarterFinals: 'Quarter-Finals',
      semiFinals: 'Semi-Finals',
      grandFinal: 'Grand Final',
      advanceWinner: 'Advance Winner ➜',
      matchScore: 'Score',
      vs: 'VS',
      winner: 'WINNER',
      tbd: 'Awaiting Winner...',
      championTitle: '🏆 TOURNAMENT CHAMPION 👑',
      championSubtitle: 'Glorious congratulations to the victorious team after an epic performance!',
      closeChampion: 'Close & Continue',
      noTournamentTitle: 'No Active Tournament',
      noTournamentSubtitle: 'Generate teams first, then tap "Create Tournament" to automatically construct an esports elimination bracket.',
    },
    finger: {
      title: 'Holographic Finger Chooser',
      subtitle: 'The most futuristic multi-touch interaction environment for instant decisions and live team splits',
      modeLabel: 'Chooser Game Mode',
      modeWinners: 'Choose Winners 👑',
      modePairs: 'Who Is With Who 🤝',
      modeTeams: 'Split Into Teams ⚔️',
      winnersCount: 'Number of Winners',
      teamsCount: 'Number of Teams',
      waitingMessage: 'Place fingers on the screen together',
      waitingHint: 'Requires at least 2 fingers to trigger automatic countdown',
      activeTouches: 'Active Holographic Nodes',
      countdown: 'Locking In...',
      simulateBtn: '🧪 Multi-Finger Simulator (Test Mode)',
      clearTouches: 'Clear Touches ✕',
      resultTitle: 'Decision Locked In!',
      winnerBadge: 'Winner 👑',
      pairBadge: 'Linked Duo 🤝',
      teamBadge: 'Team',
      againBtn: 'Draw Again 🔄',
    },
    oracle: {
      title: 'Digital Decision Oracle',
      subtitle: 'Smart random selector for deciding who starts, post-match food, games to play, or custom choices',
      inputPlaceholder: 'Type a choice and tap Add...',
      addOptionBtn: 'Add Option +',
      quickQuestions: 'Preset Question Templates:',
      currentOptions: 'Active Choice Pool:',
      minOptionsHint: 'Add at least 2 options to trigger the Oracle',
      ctaDecide: 'Awaken the Oracle 🔮',
      step1: 'Scanning options and analyzing entropy...',
      step2: 'Running quantum probability engine...',
      step3: 'Decision finalized successfully!',
      decisionTitle: 'The Oracle Has Decided:',
      decideAgain: 'Consult Oracle Again 🎲',
    },
    history: {
      title: 'Saved Formations Archive',
      subtitle: 'Chronological timeline of your previously generated rosters and team distributions',
      emptyTitle: 'No Saved Formations',
      emptySubtitle: 'When generating teams, tap "Save to History" and they will be archived here for one-tap restoration.',
      clearAllBtn: 'Clear All History 🗑️',
      restoreBtn: 'Restore Formation 🔄',
      deleteBtn: 'Delete',
      savedOn: 'Saved on',
      membersCount: 'Members',
      teamsCount: 'Teams',
      confirmClearTitle: 'Clear All Saved History?',
      confirmClearDesc: 'This will permanently remove all archived formations. This action cannot be undone.',
      confirmYes: 'Yes, Clear All',
      confirmCancel: 'Cancel',
    },
    settings: {
      title: 'Control Center & Settings',
      subtitle: 'Customize the glassmorphic theme, generative audio synthesis, language, and data backups',
      themeSection: 'Glassmorphism Theme Gallery (7 Themes)',
      themeApplied: 'Active Theme',
      applyThemeBtn: 'Apply Theme',
      soundSection: 'Haptics & Sound Feedback',
      soundTitle: 'Tactile Haptics & Sound Engine',
      soundDesc: 'Haptic feedback pulses and tactical alert sounds on taps, generation, and tournament victory',
      soundOn: 'Enabled',
      soundOff: 'Muted',
      langSection: 'Language & Layout Direction',
      langArabic: 'العربية (RTL)',
      langEnglish: 'English (LTR)',
      backupSection: 'Data Backup & Portability',
      backupDesc: 'Export all player rosters, active teams, and history to a portable JSON file or restore a backup',
      exportJsonBtn: 'Export Backup (JSON) 📥',
      importJsonBtn: 'Import Backup (JSON) 📤',
      dangerSection: 'Danger Zone',
      factoryResetBtn: 'Factory Reset & Wipe All Data ⚠️',
      aboutSection: 'About TEAM ME PRO',
      aboutText: 'TEAM ME PRO is an elite sports-tech and social decision mobile platform engineered with 2026 mobile UI/UX standards, glassmorphism, and competitive balancing algorithms.',
      version: 'Version 2.0.0 — React Native Mobile Edition',
      resetModalTitle: 'Factory Reset Warning',
      resetModalDesc: 'This will delete all saved members, active teams, tournament brackets, and history. Are you sure you want to proceed?',
      resetModalConfirm: 'Yes, Reset Everything',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ar');

  useEffect(() => {
    async function loadLang() {
      try {
        const saved = await AsyncStorage.getItem('tf_lang');
        if (saved === 'en' || saved === 'ar') {
          setLang(saved);
        }
      } catch (e) {}
    }
    loadLang();
  }, []);

  const toggleLanguage = async () => {
    const next = lang === 'ar' ? 'en' : 'ar';
    setLang(next);
    const shouldBeRTL = next === 'ar';
    try {
      await AsyncStorage.setItem('tf_lang', next);
      I18nManager.allowRTL(shouldBeRTL);
      I18nManager.forceRTL(shouldBeRTL);
    } catch (e) {}
  };

  const t = TRANSLATIONS[lang] || TRANSLATIONS.ar;
  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
